name: exo 3 manual launch
on:
  workflow_dispatch:
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: display pull_request message
        if: ${{ github.event_name == 'workflow_dispatch'}}
        run: |
          echo "Job 1 lancé manuellement"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Previous job is done        
        run: |
          echo "Job 2 lancé automatiquement"