name: exo 3
on:
  issues:
    types:
      - opened

jobs:
  display_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: detect trigger
        run: |
          echo "event name is:" ${{ github.event_name }}
          echo "event type is:" ${{ github.event.action }}
          

  issues:
    runs-on: ubuntu-latest
    steps:
      - name: display issue message
        if: ${{ github.event_name == 'issues' && github.event.action == 'opened' }}
        run: |
          echo 'une nouvelle issue a été crée ! (${{ github.event.issue.title }})'