name: exo 3
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - closed
    branches:
      - main
    

jobs:
  display_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: detect trigger
        run: |
          echo "event name is:" ${{ github.event_name }}
          echo "event type is:" ${{ github.event.action }}
          

  issues:
    runs-on: ubuntu-latest
    steps:
      - name: display issue message
        if: ${{ github.event_name == 'issues' && github.event.action == 'opened' }}
        run: |
          echo 'une nouvelle issue a été crée ! (${{ github.event.issue.title }})'


  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: display pull_request message
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
        run: |
          echo 'une MR a été fermée (${{ github.event.pull_request.title }} )'

  post_pull_request:
    needs: pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Previous job is done        
        run: |
          echo 'le job précédent s\'est terminé.'