name: Hello World
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: copy repo files
        uses: actions/checkout@v3

      - name: execute script  
        run: |
          chmod +x ./hello-world.sh
          ./hello-world.sh