name: issue assignated
on:
  issues:
    types:
      - assigned

jobs:
  create_issue_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Create Issue Branch
        run: git checkout -b support/${{ github.event.issue.title }} && git push origin support/${{ github.event.issue.title }}