name: issue assignated
on:
  issues:
    types:
      - assigned

jobs:
  create_issue_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Create Issue Branch
        run: |
          git branch -a
          git checkout -b support/${{ github.event.issue.number }}
          git push origin support/${{ github.event.issue.number }}