name: Matrix
on:
  workflow_dispatch:
    
jobs:
  fruits:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        couleur:
          - rouge
          - jaune
          - verte
          - violet
        fruit:
          - pomme
          - poire
          - peche
          - cerise
    steps:
      - name: display fruit full name
        run: echo ${{ matrix.fruit }} ${{ matrix.couleur }}