name: Matrix
on:
  workflow_dispatch:
    
jobs:
  fruits:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        couleur:
          - rouge
          - jaune
          - verte
        fruit:
          - pomme
          - poire
          - peche
    steps:
      - name: display fruit full name
        run: echo ${{ matrix.fruit }} ${{ matrix.couleur }}