name: delete branch
on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  delete_branch:
    if:  startsWith(github.head_ref, 'features/')
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: delete Branch
        run: |
          git push origin --delete ${{ github.head_ref }}